/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_bisection_service_BisectionServiceNativo */

#ifndef _Included_com_example_bisection_service_BisectionServiceNativo
#define _Included_com_example_bisection_service_BisectionServiceNativo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_bisection_service_BisectionServiceNativo
 * Method:    encontrarRaiz
 * Signature: (Ljava/lang/String;DDDI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_example_bisection_service_BisectionServiceNativo_encontrarRaiz
  (JNIEnv *, jobject, jstring, jdouble, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
