spring:
  application:
    name: bisection-service
  jackson:
    time-zone: America/Bogota
    locale: es_CO
  main:
    allow-circular-references: true

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health
  server:
    port: ${server.port}

# Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 90
    renewal-percent-threshold: 0.85
    enable-self-preservation: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    non-secure-port: ${server.port}
